Fix genfs build on R4.0 (again)
QubesOS/qubes-linux-kernel pull request #522
Opened 2022-01-10 03:10 UTC by DemiMarie

Fedora 25 has an old libext2fs that does not include the `*_hi` time
fields in its definition of `struct ext2_super_block`.  Only use these
fields on Fedora 32 and later.

2022-01-10 05:28 UTC, marmarek commented
Build for R4.0 failed (see CI for full message):
```
DEBUG: Creating regular file /builddir/build/BUILDROOT/kernel-latest-5.15.13-2.fc25.qubes.x86_64/var/lib/qubes/vm-kernels/5.15.13-2.fc25/modules.img
DEBUG: Bad option(s) specified: no_copy_xattrs
DEBUG: Extended options are separated by commas, and may take an argument which
DEBUG: 	is set off by an equals ('=') sign.
DEBUG: Valid extended options are:
DEBUG: 	mmp_update_interval=<interval>
DEBUG: 	num_backup_sb=<0|1|2>
DEBUG: 	stride=<RAID per-disk data chunk in blocks>
DEBUG: 	stripe-width=<RAID stride * data disks in blocks>
DEBUG: 	offset=<offset to create the file system>
DEBUG: 	resize=<resize maximum size in blocks>
DEBUG: 	packed_meta_blocks=<0 to disable, 1 to enable>
DEBUG: 	lazy_itable_init=<0 to disable, 1 to enable>
DEBUG: 	lazy_journal_init=<0 to disable, 1 to enable>
DEBUG: 	root_owner=<uid of root dir>:<gid of root dir>
DEBUG: 	test_fs
DEBUG: 	discard
DEBUG: 	nodiscard
DEBUG: 	quotatype=<quota type(s) to be enabled>
```

2022-01-10 05:30 UTC, DemiMarie commented
Fix already written; I just need to push it.

2022-01-11 00:59 UTC, marmarek requested changes

2022-01-11 00:59 UTC, marmarek commented on kernel.spec.in
> +%if 0%{?fedora} >= 32
Don't exclude sources, src.rpm should be the same regardless of where you build it.

2022-01-11 17:53 UTC, marmarek approved these changes

2022-01-11 17:54 UTC, merged