DRAFT: ESRT patches from Ard Biesheuvel
QubesOS/qubes-linux-kernel pull request #681
Opened 2022-11-19 00:48 UTC by DemiMarie

These are taken directly from Ard's emails.  Do not merge without changes, as discussed on the mailing list.

2022-11-20 16:59 UTC, marmarek commented
openQArun

2022-11-20 22:17 UTC, DemiMarie commented
@marmarek @ardbiesheuvel: if I apply patches 4 and 5 to Linus’s tree, it still boots on my test laptop.  If I apply patches 4, 5, and 6, the resulting kernel does not boot.

2022-11-20 23:46 UTC, marmarek commented
FWIW, it seems to work fine on top of 6.0.8 and Xen 4.14 _without_ ESRT patch.
Full boot log from a system (I think) not exposing ESRT table: https://openqa.qubes-os.org/tests/54117/logfile?filename=serial0.txt
And here is journal from a system with ESRT table (seems to be placed in "reserved" memory already): https://openqa.qubes-os.org/tests/54107/file/system_tests-journalctl.log (you can see `esrt: Reserving ESRT space from 0x00000000b7550298 to 0x00000000b75502f8` line there).

2022-11-21 00:41 UTC, DemiMarie commented
> FWIW, it seems to work fine on top of 6.0.8 and Xen 4.14 _without_ ESRT patch. Full boot log from a system (I think) not exposing ESRT table: https://openqa.qubes-os.org/tests/54117/logfile?filename=serial0.txt And here is journal from a system with ESRT table (seems to be placed in "reserved" memory already): https://openqa.qubes-os.org/tests/54107/file/system_tests-journalctl.log (you can see `esrt: Reserving ESRT space from 0x00000000b7550298 to 0x00000000b75502f8` line there).

The problem is that `esrt: Reserving ESRT space from 0x00000000b7550298 to 0x00000000b75502f8` is a lie.  Linux is not in charge of physical memory allocation; Xen is.  So Linux thinks it has reserved this memory but it has not.  The Xen patch reserves the ESRT, and the Linux patch checks for the ESRT having actually been reserved.

2022-11-24 04:03 UTC, marmarek commented
I haven't tested it yet, but I like the simplicity of this generic approach.

drivers/firmware/efi/esrt.c:
```
    if (!efi_enabled(EFI_MEMMAP))
        return;
```
Shouldn't the above be modified too? Or is `EFI_MEMMAP` set under Xen now?

2022-11-24 04:30 UTC, DemiMarie commented
> I haven't tested it yet, but I like the simplicity of this generic approach.
> 
> drivers/firmware/efi/esrt.c:
> 
> ```
>     if (!efi_enabled(EFI_MEMMAP))
>         return;
> ```
> 
> Shouldn't the above be modified too? Or is `EFI_MEMMAP` set under Xen now?

It does need to be modified; I added that as patch 4.  I also needed to allow ACPI memory types, as that is what Xen will be using in the future.

2022-12-18 03:49 UTC, marmarek requested changes

2022-12-18 03:49 UTC, marmarek commented on v3-0006-efi-Do-not-try-to-load-the-BGRT-under-Xen.patch
> +Subject: [PATCH v3 6/6] efi: Do not try to load the BGRT under Xen
Please drop this patch. Xen does know about BGRT table and invalidate it right now, but at some point it may avoid clobbering it.

2023-01-06 02:59 UTC, marmarek commented
PipelineRetry

2023-01-06 16:04 UTC, marmarek commented
openQArun

2023-01-15 13:11 UTC, marmarek commented
I have tested this in few configurations and it seems to work fine, specifically:
 - when started with Xen that doesn't relocate ESRT, Linux doesn't try to use it
 - when started with Xen that does relocate ESRT, it is available in dom0 too

2023-01-23 21:38 UTC, DemiMarie commented
These patches are now in efi/next.

2023-02-19 04:25 UTC, marmarek approved these changes

2023-02-19 04:26 UTC, merged